version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: 'bin/authtrail serve'
    ports:  
      - 4000:4000
    expose:
      - 4000

volumes:
  mongodb_data:
    driver: local