version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: 'bin/authtrail serve'
    ports:  
      - 4000:4000
    expose:
      - 4000

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092


  karafka_ui:
    build: .
    volumes:
      - .:/app
    depends_on:
      - kafka
      - mongodb
    command:  >
            sh -c "bundle exec karafka-web install &&
                  bundle exec rackup karafka_web.ru --host 0.0.0.0 --quiet --port 8081"
    ports:
      - '8081:8081'
    deploy:
      replicas: 1

  karafka_consumer:
    build: .
    volumes:
      - .:/app
    depends_on:
      - kafka
      - mongodb
    command: "bin/authtrail consume"
    deploy:
      replicas: 1

volumes:
  mongodb_data:
    driver: local